apiVersion: v1
kind: Secret
metadata:
  name: schema-registry-credentials
  namespace: fedramp-data-mesh
type: Opaque
data:
  truststore.password: "${TRUSTSTORE_PASSWORD_BASE64}"
  keystore.password: "${KEYSTORE_PASSWORD_BASE64}"
  key.password: "${KEY_PASSWORD_BASE64}"
