apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  namespace: fedramp-data-mesh
  labels:
    app: schema-registry
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: https
  selector:
    app: schema-registry
