apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: fedramp-data-mesh
  labels:
    app: kafka-connect
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: kafka-connect
